kubectl apply -f - <<EOF
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: runner-access
  namespace: actions-runner-system
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runner-access-binding
  namespace: actions-runner-system
subjects:
- kind: ServiceAccount
  name: default
  namespace: actions-runner-system
roleRef:
  kind: Role
  name: runner-access
  apiGroup: rbac.authorization.k8s.io
EOF
