name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:

    runs-on: ubuntu-latest
    steps:
      - name: Shorten commit id
        shell: bash
        run: echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: manoj1989/python-app:${{ env.COMMIT_ID }}
    
    outputs:
      commit_id: ${{ env.COMMIT_ID }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Modify value
        shell: bash
        run: |
          echo ${{needs.ci.outputs.COMMIT_ID}}
          pip install yq
          yq -Yi '.imgae.tag' = "${{needs.ci.outputs.COMMIT_ID}}" charts/python-app/values.yaml

      - name: Install kubectl
        shell: bash
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      - name: Install ArgoCD CLI
        shell: bash
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: ArgoCD App Sync
        shell: bash
        run: |
          echo "Logging in to ArgoCD (core mode)..."
          argocd login my-release-argocd-server.argocd \
          --insecure \
          --grpc-web \
          --username admin \
          --password "admin123"

          echo "Syncing ArgoCD app..."
          argocd app sync python-app