name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubantu-latest
    steps:
      - name: Shorten commit id
        shell: bash
        run: echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"                 
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: manoj1989/python-app:${{ env.COMMIT_ID }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Argocd app Sync
        shell: bash
        run: |
          argocd login https://my-release-argocd-server.argocd \
            --insecure  \
            --username admin \
            --password {{secrets.ARGO_PASSWORD}}
          argocd app sync python-app
          

